### PR TITLE
added queue store and abstract jackson serializer

### PR DESCRIPTION
**Pull request by juliannaelamb**

### CODE REVIEW

**Comment by juliannaelamb** [comment]
@geekbeast

**Comment by juliannaelamb** [comment]
@makosblade @geekbeast can I get some code review on this when you get a chance please? going to need this to be able to successfully build my other pr's.

**Comment by juliannaelamb** [comment]
@makosblade @geekbeast realized that I'm going to have to change this to hyperdex right. So it looks like I'll need to write a HyperdexBaseJacksonQueueStore, based on HyperdexBaseJacksonKeyValueMapStore is that right?

**Comment by geekbeast** [comment]
LGTM

**Pull request merged**
